title: "Hi, I'm Keoni"
remote_theme: just-the-docs/just-the-docs
color_scheme: catppuccin

url: https://obiwankeoni.github.io

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

footer_content: "Copyright &copy; 2023 Keoni Garner."

callouts:
  highlight:
    color: yellow
  info:
    title: Info
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: yellow
