title: "Hi, I'm Keoni"
remote_theme: just-the-docs/just-the-docs
include: ['_pages']
color_scheme: catppuccin

url: https://obiwankeoni.github.io

logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

footer_content: "Copyright &copy; 2023 Keoni Garner."

callouts:
  warning:
    title: Warning
    color: red
