title: Disjointed Thoughts
remote_theme: just-the-docs/just-the-docs
include: ['_pages']
color_scheme: catppuccin

url: https://obiwankeoni.github.io

footer_content: "Copyright &copy; 2023 Keoni Garner."

callouts:
  warning:
    title: Warning
    color: red
